<?xml version='1.0'?>


<robot name="vehicle" xmlns:xacro="http://www.ros.org/wiki/xacro">

 
  <xacro:include filename="$(find simulation)/models/vehicle/vehicle.gazebo" />
  <xacro:include filename="$(find simulation)/models/vehicle/materials.xacro"   />
  <xacro:include filename="$(find simulation)/models/vehicle/macros.xacro"      />
  <xacro:include filename="$(find simulation)/models/vehicle/parameter.xacro"   />

 
  <link name='base_link'>
    <pose>0 0 0 0 0 0</pose>
  </link>
  <joint type="fixed" name="base_link_to_chassis">
    <child link="chassis_link"/>
    <parent link="base_link"/>
  </joint>

  
  <link name='chassis_link'>
    <pose>0 0 0 0 0 0</pose>
   
    <inertial>
      <mass value="${m_chassis}"/>
      <xacro:box_inertia m="${m_chassis}" x="${x_chassis}" y="${y_chassis}" z="${z_chassis}"/>
    </inertial>
    
    <collision name='collision'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${x_chassis} ${y_chassis} ${z_chassis}"/>
      </geometry>
    </collision>
   
    <visual name='base_link_visual'>
	  <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${x_chassis} ${y_chassis} ${z_chassis}"/>
      </geometry>
    </visual>

    <collision name='wall11_collision'>
      <origin xyz="${-(x_chassis/2)+(wall_thickness/2)} 0 ${(z_chassis/2)+(wall_height/2)} " rpy=" 0 0 0"/>
      <geometry>
        <box size="${wall_thickness} ${y_chassis} ${wall_height}"/>
      </geometry>
    </collision>
   
    <visual name='wall11_visual'>
	  <origin xyz="${-(x_chassis/2)+(wall_thickness/2)} 0 ${(z_chassis/2)+(wall_height/2)}" rpy=" 0 0 0"/>
      <geometry>
        <box size="${wall_thickness} ${y_chassis} ${wall_height}"/>
      </geometry>
    </visual>

    <collision name='wall12_collision'>
      <origin xyz="${(x_chassis/2)-(wall_thickness/2)} 0 ${(z_chassis/2)+(wall_height/2)}" rpy=" 0 0 0"/>
      <geometry>
        <box size="${wall_thickness} ${y_chassis} ${wall_height}"/>
      </geometry>
    </collision>
   
    <visual name='wall12_visual'>
	    <origin xyz="${(x_chassis/2)-(wall_thickness/2)} 0 ${(z_chassis/2)+(wall_height/2)}" rpy=" 0 0 0"/>
      <geometry>
        <box size="${wall_thickness} ${y_chassis} ${wall_height}"/>
      </geometry>
    </visual>

    <collision name='wall21_collision'>
      <origin xyz="0 ${(y_chassis/2)-(wall_thickness/2)-wall_offset} ${(z_chassis/2)+(wall_height/2)}" rpy=" 0 0 0"/>
      <geometry>
        <box size="${x_chassis-2*wall_thickness} ${wall_thickness} ${wall_height}"/>
      </geometry>
    </collision>
   
    <visual name='wall21_visual'>
	  <origin xyz="0 ${(y_chassis/2)-(wall_thickness/2)-wall_offset} ${(z_chassis/2)+(wall_height/2)}" rpy=" 0 0 0"/>
      <geometry>
        <box size="${x_chassis-2*wall_thickness} ${wall_thickness} ${wall_height}"/>
      </geometry>
    </visual>

    <collision name='wall22_collision'>
      <origin xyz="0 ${-(y_chassis/2)+(wall_thickness/2)-wall_offset} ${(z_chassis/2)+(wall_height/2)}" rpy=" 0 0 0"/>
      <geometry>
        <box size="${x_chassis-2*wall_thickness} ${wall_thickness} ${wall_height}"/>
      </geometry>
    </collision>
   
    <visual name='wall22_visual'>
	  <origin xyz="0 ${-(y_chassis/2)+(wall_thickness/2)-wall_offset} ${(z_chassis/2)+(wall_height/2)}" rpy=" 0 0 0"/>
      <geometry>
        <box size="${x_chassis-2*wall_thickness} ${wall_thickness} ${wall_height}"/>
      </geometry>
    </visual>
  </link>

  
  <link name="left_wheel">
    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${r_wheel}" length="${h_wheel}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
            <slip1>0.0</slip1>
            <slip2>0.0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>
    <visual name="left_wheel_visual">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${r_wheel}" length="${h_wheel}"/>
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <mass value="${m_wheel}"/>
      <cylinder_inertia m="${m_wheel}" r="${r_wheel}" h="${h_wheel}"/>
      <xacro:cylinder_inertia m="${m_wheel}" r="${r_wheel}" h="${h_wheel}"/>
    </inertial>
  </link>

  <link name="right_wheel">
    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${r_wheel}" length="${h_wheel}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
            <slip1>0.0</slip1>
            <slip2>0.0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>
    <visual name="right_wheel_visual">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${r_wheel}" length="${h_wheel}"/>
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <mass value="${m_wheel}"/>
      <cylinder_inertia m="${m_wheel}" r="${r_wheel}" h="${h_wheel}"/>
      <xacro:cylinder_inertia m="${m_wheel}" r="${r_wheel}" h="${h_wheel}"/>
    </inertial>
  </link>

  <link name="right_wheel1">
    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${r_wheel}" length="${h_wheel}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
            <slip1>0.0</slip1>
            <slip2>0.0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>
    <visual name="right_wheel_visual">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${r_wheel}" length="${h_wheel}"/>
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <mass value="${m_wheel}"/>
      <cylinder_inertia m="${m_wheel}" r="${r_wheel}" h="${h_wheel}"/>
      <xacro:cylinder_inertia m="${m_wheel}" r="${r_wheel}" h="${h_wheel}"/>
    </inertial>
  </link>

  <link name="left_wheel1">
    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${r_wheel}" length="${h_wheel}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
            <slip1>0.0</slip1>
            <slip2>0.0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>
    <visual name="left_wheel_visual">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${r_wheel}" length="${h_wheel}"/>
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <mass value="${m_wheel}"/>
      <cylinder_inertia m="${m_wheel}" r="${r_wheel}" h="${h_wheel}"/>
      <xacro:cylinder_inertia m="${m_wheel}" r="${r_wheel}" h="${h_wheel}"/>
    </inertial>
  </link>

  <joint type="continuous" name="left_wheel_hinge">
    <origin xyz="${-x_chassis/3} ${y_chassis/2+h_wheel/2} ${r_wheel/2-z_chassis/2}" rpy="0 0 0"/>
    <child link="left_wheel"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>

  <joint type="continuous" name="left_wheel_hinge1">
    <origin xyz="${+x_chassis/3} ${y_chassis/2+h_wheel/2} ${r_wheel/2-z_chassis/2}" rpy="0 0 0"/>
    <child link="left_wheel1"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>

  <joint type="continuous" name="right_wheel_hinge">
    <origin xyz="${-x_chassis/3} ${-y_chassis/2-h_wheel/2} ${r_wheel/2-z_chassis/2}" rpy="0 0 0"/>
    <child link="right_wheel"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>

  <joint type="continuous" name="right_wheel_hinge1">
    <origin xyz="${+x_chassis/3} ${-y_chassis/2-h_wheel/2} ${r_wheel/2-z_chassis/2}" rpy="0 0 0"/>
    <child link="right_wheel1"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>

</robot>